Feature/style counter
isdi-coders-202207-bcn-coding-adventure/xifre-font-front pull request #4
Opened 2022-08-22 13:24 UTC by xfontr

2022-08-22 13:42 UTC, mariogl requested changes

2022-08-22 13:42 UTC, mariogl commented on src/components/Counter/CounterStyled.ts
> +    &-item > *:first-child {
¿Por qué este selector teniendo una clase?

2022-08-22 13:42 UTC, mariogl commented on src/components/Counter/CounterStyled.ts
> +      font-family: rajdhani, sans-serif;
¿Por qué esta font-family?

2022-08-22 13:50 UTC, xfontr commented on src/components/Counter/CounterStyled.ts
> +      font-family: rajdhani, sans-serif;
Era la más parecida a la del modelo (de entre las opciones gratis).

2022-08-22 13:52 UTC, xfontr commented on src/components/Counter/CounterStyled.ts
> +    &-item > *:first-child {
He optado por enfocarlo así porque cada clase tenía un nombre distinto, y de esta forma evitaba tener que estilizar cuatro clases distintas.

2022-08-22 14:00 UTC, luisdudamel commented on src/components/Counter/CounterStyled.ts
> +      font-family: rajdhani, sans-serif;
@xfontr Ya hemos establecido cual es la fuente a utilizar.

2022-08-22 14:04 UTC, mariogl commented on src/components/Counter/CounterStyled.ts
> +    &-item > *:first-child {
Si son el mismo elemento y se ve igual, tienen que tener la misma clase.

2022-08-22 14:09 UTC, xfontr commented on src/components/Counter/CounterStyled.ts
> +    &-item > *:first-child {
Vale, comprendido, ya lo he vuelto a subir

2022-08-22 14:10 UTC, facundotolosa approved these changes
**Fase 4:** _Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente._

2022-08-22 14:17 UTC, mariogl approved these changes

2022-08-22 14:18 UTC, merged

2022-08-24 16:03 UTC, dawgun commented on src/components/Counter/CounterStyled.ts
> +    &-item__number {
El nesteo debería &__number por ejemplo, ya que está siendo un hijo de counter-item.